# Generated by Django 4.0.4 on 2022-05-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
